package com.dhanush.twitterclone.model

val DATA_USERS= "Users"
val DATA_USERS_EMAIL = "email"
val DATA_USER_USERNAME="username"
val DATA_USER_IMAGE_URL ="imageUrl"
val DATA_USERS_HASHTAGS="followHashTags"
val DATA_USERS_FOLLOW = "followUsers"
val DATA_IMAGES = "ProfileImages"
val DATA_TWEETS = "Tweets"
val DATA_TWEET_USER_IDS = "userIds"
val DATA_TWEET_HASHTAGS = "hashtags"
val DATA_TWEET_LIKES = "likes"
val DATA_TWEET_IMAGE_URL ="imageUrl"
val DATA_TWEET_IMAGES = "TweetImages"
